In [2]:
#数组
import numpy as np #导入 Numpy 库
arr1 = np.array([1,2,3,4])
print('创建的数组为：',arr1)

创建的数组为： [1 2 3 4]


In [3]:
#二维数组
arr2 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print('创建的数组为：\n',arr2)

创建的数组为：
 [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [12]:
print('数组维度为：',arr2.shape)  #数组结构

数组维度为： (3, 4)


In [13]:
print('数组类型为：',arr2.dtype) #查看数组类型

数组类型为： int32


In [14]:
print('数组元素个数：',arr2.size)

数组元素个数： 12


In [16]:
print('每个元素大小：',arr2.itemsize)

每个元素大小： 4


In [19]:
#重置shape属性
arr2.shape = 4,3
print('重新设置shape后的arr2为\n',arr2)

重新设置shape后的arr2为
 [[ 1  2  3]
 [ 4  4  5]
 [ 6  7  7]
 [ 8  9 10]]


In [20]:
#使用 range 函数创建等差数组
#(头，尾，公差)
print('',np.arange(0,1,0.1))

 [ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9]


In [22]:
# 使用 linspace/logspace 函数创建等比数列数组
#(头，尾，个数)
print('',np.linspace(0,1,12))

 [ 0.          0.09090909  0.18181818  0.27272727  0.36363636  0.45454545
  0.54545455  0.63636364  0.72727273  0.81818182  0.90909091  1.        ]


In [26]:
#使用 zero 函数创建全为0的数组
print(np.zeros((2,3)))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [27]:
#使用 eye / diag函数创建的数组
#除对角线外元素都为0
print(np.eye(3))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [29]:
#使用 ones 函数创建数组
print(np.ones((5,3)))

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [30]:
#生成随机数
print('生成的随机数组为',np.random.random(100))

生成的随机数组为 [ 0.58013984  0.83050408  0.33132434  0.76911625  0.97576666  0.97196713
  0.66011066  0.50360851  0.22378812  0.94331459  0.71529971  0.82373564
  0.70231244  0.04370703  0.36012807  0.65834629  0.74532395  0.45483411
  0.8273944   0.58346085  0.34279598  0.5159995   0.20190806  0.90988752
  0.09225111  0.41344542  0.56510818  0.74956966  0.98269017  0.50421209
  0.8175808   0.74591227  0.46314369  0.23110277  0.36945689  0.91438663
  0.75775532  0.70221501  0.96979601  0.34188335  0.63980066  0.16449619
  0.17222234  0.54026047  0.639841    0.60704452  0.80506502  0.87396994
  0.16188583  0.0303184   0.27383231  0.14906868  0.98242921  0.69405775
  0.17812657  0.53750851  0.14699729  0.89815226  0.66596917  0.57617598
  0.42327916  0.74530757  0.38553879  0.15475785  0.34507253  0.49137294
  0.89078959  0.97944579  0.28886714  0.87389207  0.09095529  0.91659909
  0.80844732  0.30116192  0.12579261  0.93174063  0.78833205  0.88622985
  0.70696333  0.32022404  0.01532409  0.62

In [32]:
#服从均匀分布
print(np.random.randn(10,5))

[[-0.50616883  1.08559969 -2.79163158  0.43004461  0.68728918]
 [-2.29514627 -0.52346205  0.20449904  0.73983668 -0.11653152]
 [ 0.47508788 -0.01464888  0.72057113 -0.18867898  1.43256011]
 [ 0.27242703 -0.12804465 -0.29478841  0.37824659  0.27593394]
 [-1.14692134  0.95669586  0.15995851  0.08116906  0.01887918]
 [-0.32859943 -0.18951421  0.35953577 -0.81166762  0.80794489]
 [-1.17909613 -1.84036931  2.26594004  1.03855276  1.00762758]
 [ 0.80934121 -0.44467366 -0.26213941  0.54003622 -0.06434653]
 [-0.72051541 -0.0181182   0.80087985  2.05874241 -0.1797017 ]
 [ 0.11910769  0.09894383  0.20015278 -2.73545065  0.71593682]]


In [33]:
#生成限定上下限
print(np.random.randint(2,10,size=[2,5]))

[[7 4 7 2 4]
 [7 2 9 7 8]]


In [5]:
## 索引
arr = np.arange(10)
print(arr[5])
print(arr[3:5])
print(arr[:5])

5
[3 4]
[0 1 2 3 4]


In [7]:
# 多维数组
arr = np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11]])
print('创建的多维数组：\n',arr)

创建的多维数组：
 [[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]]


In [8]:
print(arr[0,3:5]) #第0行第三四列

[4 5]


In [9]:
print(arr[1:,2:]) #第2、3行第3-5列元素

[[ 6  7  8]
 [ 9 10 11]]


In [10]:
print(arr[:,2]) #第2列

[3 6 9]


In [11]:
# 改变数组形状
arr = np.arange(12)
print(arr)
print(arr.reshape(3,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
#展平: ravel或flatten
arr = np.arange(12).reshape(3,4)
print(arr)
print(arr.ravel())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [15]:
#split函数分割
print('横向分割：',np.split(arr,2,axis=1))

横向分割： [array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [20]:
print('纵向分割：',np.split(arr,2,axis=0))

ValueError: array split does not result in an equal division